apiVersion: v1
kind: Service
metadata:
  name: easy-kart-redis-service
  labels:
    app: easy-kart-redis
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: easy-kart-redis
